# Generated by Django 5.2.10 on 2026-02-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
