# Generated by Django 5.2.10 on 2026-02-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='average_transaction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='usual_transaction_hour_end',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='usual_transaction_hour_start',
            field=models.IntegerField(default=9),
        ),
    ]
