# Generated by Django 5.2.10 on 2026-02-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_risk_score_alter_transaction_bill_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
